### ISSUE TITLE
view update handler state naming

### ISSUE THREAD

**Issue by aklikic** [lightbend/akkaserverless-java-sdk#317] opened 2021-09-09 07:09 UTC
view update handler uses `state` as a name for the representation of the view row.
This naming could be missleading by relating it to `domain state` and these are two different things.
Even our examples use `doman state` grpc message as a view row representation supporting this relation. 

For example in `java-eventsources-customer-registry` `customer_view.proto`, `domain.CustomerState` is used as a view row representation:
```
 rpc ProcessCustomerCreated(domain.CustomerCreated) returns (domain.CustomerState) {
    option (akkaserverless.method).eventing.in = {
      event_sourced_entity: "customers"
    };
    option (akkaserverless.method).view.update = {
      table: "customers"
      transform_updates: true
    };
  }
```
And in view update handler class `CustomerByNameView` methods use state naming (`emptyState()`,  parametar in `updateEffect` methods).
This all indicates that what we store in the view is a `state`.
In some cases it will be `state` but in others it will be some enriched representation or just a relation.
So chaging the name `state` to something else (like `view`, `viewModel` or `representation`) would be much more descriptive to what it represents. 
Also our view examples should not use `domain state` gprc message but a dedicated gprc message for that view model.

**Comment by johanandren** [comment] 2021-09-09 10:12
I discussed this with @mckeeh3 a bit recently. It _is_ the state of the view so not sure I agree we should change that naming but I think the second part with the samples re-using the domain representation as the view representation is the actually the cause of the confusion. With a separate type there is no way you'd expect it to be the state of the entity you subscribe to since the types are note the same. It's also bad practice to "leak" the internal domain type through the API, so we shouldn't do that in the samples.

**Comment by patriknw** [comment] 2021-09-09 12:19
Good point that it's better to have a different state representation for the view, and not reuse the state representation from the entity.

However, for value entities that requires `transform_updates=true` and it was kind of neat to have that automatic.

**Comment by johanandren** [comment] 2021-09-10 08:26
For samples where `transform_updates=false` there shouldn't be any confusion because then there is no method and no need to implement `emptyState()`.

So the only possible scenario with confusion is in samples with `transform_updates=true` but anyway using the domain types for the view. I think we should update that sample (it's only `java-eventsourced-customer-registry`) to have an API type for the view state instead.

In the future when we have a transformation for the query result as well, that having the domain type in the view will be an ok decision since the result transformation can then turn it into an "API" type.

**Comment by patriknw** [comment] 2021-09-10 08:34
Sounds good.

> In the future when we have a transformation for the query result as well, that having the domain type in the view will be an ok decision since the result transformation can then turn it into an "API" type.

That is true, but it will be more performant to store the right things instead of transforming when reading.

**Comment by patriknw** [comment] 2021-09-10 12:20
@johanandren can we close this, or is there more follow up?

**Comment by johanandren** [comment] 2021-09-10 12:22
Let's close it!

**Closed by johanandren** 2021-09-10 12:22 UTC
